Play = 'play'
Pass = 'pass'
Draw = 'draw'
Discard = 'discard'
Create = 'create'
Shuffle = 'shuffle'
Resolve = 'resolve'
Win = 'win'
Lose = 'lose'
Tie = 'tie'

# Birth = 'play'
# Inspire = 'play'
# Nourish = 'play'

# Meow = 'play'
# Yell = 'play'
# BoneSnap = 'play'
# Bird = 'play'
# Drown = 'play'
# Fire = 'play'
# Reset = 'play'
# Crowd = 'play'
# Sarcophagus = 'play'

Cut = 'discard'